name: Android APK (Debug)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-apk:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Install Capacitor packages into THIS repo (needed for npx cap add)
      - name: Install Capacitor deps
        run: |
          npm pkg set name="all-in-one-calculator" >/dev/null 2>&1 || true
          npm i --no-audit --no-fund @capacitor/core @capacitor/cli @capacitor/android

      # Create the android/ project (idempotent)
      - name: Capacitor add android
        run: npx cap add android --yes

      # Sync web files into android/ and ensure Gradle wrapper is executable
      - name: Capacitor sync
        run: npx cap sync android

      - name: Make Gradle wrapper executable
        run: chmod +x android/gradlew

      # Build the debug APK
      - name: Build debug APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
